project_name: set-property
before:
  hooks:
    - go mod download
builds:
  - binary: set-property
    env:
      # to allow for alpine/musl use
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
changelog:
  filters:
    exclude:
      - '^build:'
      - '^ci:'