name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"
  schedule:
    - cron: 0 4 * * SUN

jobs:
  build:
    uses: itzg/github-workflows/.github/workflows/go-test.yml@main
    with:
      go-version: "1.24.4"
